### ISSUE TITLE
API Exception thrown by Data Catalog API

### ISSUE THREAD

**Issue by Ace-Bansal** [GoogleCloudPlatform/DataflowTemplates#135]
I'm trying to setup [this pipeline](https://github.com/GoogleCloudPlatform/DataflowTemplates/tree/master/v2/cdc-parent) to connect mysql to BQ using Cloud Pub/Sub and Dataflow on my local system (Ubuntu 18.04). I keep running into a lot of errors, but have been able to solve them sooner or later. However I have been facing this latest error for a couple of days now but haven't been able to solve it. There seems to be some problem with the Data Catalog API. I have already enabled that particular API, I am using a service account that has all the permissions. My credentials are saved in the env variable GOOGLE_APPLICATION_CREDENTIALS and they're working, I have verified by following [this link](https://cloud.google.com/docs/authentication/getting-started).

Here's my stack trace, any help would be really appreciated:

```CANT LOOKUP ENTRYcom.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: No permission to lookup Entry "projects/pubsubpoc/locations/global/entryGroups/@pubsub/entries/cHJvamVjdHMvcHVic3VicG9jL3RvcGljcy9leHBvcnRfZGVtb190b3VybGFuZGlzaC50b3VybGFuZGlzaC5jdXJyZW5jeQ" or it does not exist.
com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: No permission to lookup Entry "projects/pubsubpoc/locations/global/entryGroups/@pubsub/entries/cHJvamVjdHMvcHVic3VicG9jL3RvcGljcy9leHBvcnRfZGVtb190b3VybGFuZGlzaC50b3VybGFuZGlzaC5jdXJyZW5jeQ" or it does not exist.
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:55)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1349)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1024)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:866)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:711)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:520)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:495)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at com.google.cloud.datacatalog.v1beta1.DataCatalogClient.lookupEntry(DataCatalogClient.java:1254)
		at com.google.cloud.dataflow.cdc.common.DataCatalogSchemaUtils.lookupPubSubEntry(DataCatalogSchemaUtils.java:100)
		at com.google.cloud.dataflow.cdc.common.DataCatalogSchemaUtils.setSchemaForPubSubTopic(DataCatalogSchemaUtils.java:44)
		at com.google.cloud.dataflow.cdc.connector.PubSubChangeConsumer.handleBatch(PubSubChangeConsumer.java:139)
		at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:826)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		... 3 more
Caused by: io.grpc.StatusRuntimeException: PERMISSION_DENIED: No permission to lookup Entry "projects/pubsubpoc/locations/global/entryGroups/@pubsub/entries/cHJvamVjdHMvcHVic3VicG9jL3RvcGljcy9leHBvcnRfZGVtb190b3VybGFuZGlzaC50b3VybGFuZGlzaC5jdXJyZW5jeQ" or it does not exist.
	at io.grpc.Status.asRuntimeException(Status.java:533)
	... 23 more
20/05/30 15:20:32 ERROR common.DataCatalogSchemaUtils: ApiException thrown by Data Catalog API:
com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: No permission to lookup Entry "projects/pubsubpoc/locations/global/entryGroups/@pubsub/entries/cHJvamVjdHMvcHVic3VicG9jL3RvcGljcy9leHBvcnRfZGVtb190b3VybGFuZGlzaC50b3VybGFuZGlzaC5jdXJyZW5jeQ" or it does not exist.
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:55)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1349)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1024)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:866)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:711)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:520)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:495)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at com.google.cloud.datacatalog.v1beta1.DataCatalogClient.lookupEntry(DataCatalogClient.java:1254)
		at com.google.cloud.dataflow.cdc.common.DataCatalogSchemaUtils.lookupPubSubEntry(DataCatalogSchemaUtils.java:100)
		at com.google.cloud.dataflow.cdc.common.DataCatalogSchemaUtils.setSchemaForPubSubTopic(DataCatalogSchemaUtils.java:44)
		at com.google.cloud.dataflow.cdc.connector.PubSubChangeConsumer.handleBatch(PubSubChangeConsumer.java:139)
		at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:826)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		... 3 more
Caused by: io.grpc.StatusRuntimeException: PERMISSION_DENIED: No permission to lookup Entry "projects/pubsubpoc/locations/global/entryGroups/@pubsub/entries/cHJvamVjdHMvcHVic3VicG9jL3RvcGljcy9leHBvcnRfZGVtb190b3VybGFuZGlzaC50b3VybGFuZGlzaC5jdXJyZW5jeQ" or it does not exist.
	at io.grpc.Status.asRuntimeException(Status.java:533)
	... 23 more
20/05/30 15:20:32 ERROR embedded.EmbeddedEngine: Stopping connector after error in the application's handler method: A problem occurred when communicating with Cloud Data Catalog
java.lang.InterruptedException: A problem occurred when communicating with Cloud Data Catalog
	at com.google.cloud.dataflow.cdc.connector.PubSubChangeConsumer.handleBatch(PubSubChangeConsumer.java:142)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:826)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
20/05/30 15:20:32 ERROR mysql.SnapshotReader: Failed due to error: Aborting snapshot due to error when last running 'SELECT * FROM `tourlandish`.`currency_conversion_rate`': Can''t call rollback when autocommit=true
org.apache.kafka.connect.errors.ConnectException: Can''t call rollback when autocommit=true Error code: 0; SQLSTATE: 08003.
	at io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:230)
	at io.debezium.connector.mysql.AbstractReader.failed(AbstractReader.java:208)
	at io.debezium.connector.mysql.SnapshotReader.execute(SnapshotReader.java:721)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.sql.SQLNonTransientConnectionException: Can''t call rollback when autocommit=true
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:1851)
	at io.debezium.connector.mysql.SnapshotReader.execute(SnapshotReader.java:629)
	... 3 more
[WARNING] thread Thread[Abandoned connection cleanup thread,5,com.google.cloud.dataflow.cdc.connector.App] was interrupted but is still alive after waiting at least 15000msecs
[WARNING] thread Thread[Abandoned connection cleanup thread,5,com.google.cloud.dataflow.cdc.connector.App] will linger despite being asked to die via interruption
[WARNING] thread Thread[Gax-1,5,com.google.cloud.dataflow.cdc.connector.App] will linger despite being asked to die via interruption
[WARNING] thread Thread[grpc-default-worker-ELG-1-1,5,com.google.cloud.dataflow.cdc.connector.App] will linger despite being asked to die via interruption
[WARNING] thread Thread[grpc-default-executor-0,5,com.google.cloud.dataflow.cdc.connector.App] will linger despite being asked to die via interruption
[WARNING] thread Thread[grpc-default-worker-ELG-1-2,5,com.google.cloud.dataflow.cdc.connector.App] will linger despite being asked to die via interruption
[WARNING] thread Thread[grpc-default-worker-ELG-1-3,5,com.google.cloud.dataflow.cdc.connector.App] will linger despite being asked to die via interruption
[WARNING] thread Thread[Gax-2,5,com.google.cloud.dataflow.cdc.connector.App] will linger despite being asked to die via interruption
[WARNING] thread Thread[Gax-3,5,com.google.cloud.dataflow.cdc.connector.App] will linger despite being asked to die via interruption
[WARNING] thread Thread[Gax-4,5,com.google.cloud.dataflow.cdc.connector.App] will linger despite being asked to die via interruption
[WARNING] NOTE: 9 thread(s) did not finish despite being asked to  via interruption. This is not a problem with exec:java, it is a problem with the running code. Although not serious, it should be remedied.
[WARNING] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=com.google.cloud.dataflow.cdc.connector.App,maxpri=10]
java.lang.IllegalThreadStateException
    at java.lang.ThreadGroup.destroy (ThreadGroup.java:776)
    at org.codehaus.mojo.exec.ExecJavaMojo.execute (ExecJavaMojo.java:321)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  19:22 min
[INFO] Finished at: 2020-05-30T15:20:47+05:30
[INFO] ------------------------------------------------------------------------```

**Comment by pabloem** [comment]
hi @Ace-Bansal - I'll take a look at this tomorrow morning. Thanks for your report!

**Comment by pabloem** [comment]
Okay, I understand you might have tried this, but I'd like to make sure we've tried everything:

- What privileges did you give to your service account credentials?
- Did you try using a high-privileges service account? (e.g. project owner service account)

It could be a bug with the auth checks for Data Catalog?

**Comment by Ace-Bansal** [comment]
@pabloem the service account is the owner of the project. I tried running the connector on a VM in GCP with the database on a Cloud SQL instance and got this:
```ekansh_bansal@debezium-vm2:~/DataflowTemplates/v2/cdc-parent$ mvn exec:java -pl cdc-embedded-connector \
>     -Dexec.args="/home/ekansh_bansal/file.properties"                                                                                                                                                                                    
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.google.cloud.dataflow.cdc:cdc-change-applier:jar:0.1
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:exec-maven-plugin is missing. @ line 30, column 15
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.google.cloud.dataflow.cdc:cdc-embedded-connector:jar:0.1
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:exec-maven-plugin is missing. @ line 37, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] --------< com.google.cloud.dataflow.cdc:cdc-embedded-connector >--------
[INFO] Building cdc-embedded-connector 0.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ cdc-embedded-connector ---
Logger Binding: org.slf4j.impl.Log4jLoggerFactory@7f111f1c
org.slf4j.impl.Log4jLoggerFactory
Jun 03, 2020 6:45:32 AM com.github.shyiko.mysql.binlog.BinaryLogClient connect
INFO: Connected to 34.73.5.84:3306 at 15a56360-a4c9-11ea-a7c9-42010a8e0015:1-13441 (sid:5935, cid:5924)```

It's not giving any other feedback. Is this the expected behaviour or am I missing something? I should mention that I've just deployed the connector so far and not the Dataflow pipeline yet.

**Comment by Ace-Bansal** [comment]
![image](https://user-images.githubusercontent.com/34866483/83684951-73702c80-a605-11ea-822a-57674f2bd52d.png)

I think the job is running fine, but I don't understand what should be the expected behaviour? I tried inserting a new row in the table that I've connected this pipeline to, but I can't see anything in the logs.

**Comment by hallaji** [comment]
I am receiving similar warning. What would be the cause for this?

```
[WARNING] NOTE: 27 thread(s) did not finish despite being asked to  via interruption. This is not a problem with exec:java, it is a problem with the running code. Although not serious, it should be remedied.
[WARNING] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=com.google.cloud.dataflow.cdc.applier.CdcToBigQueryChangeApplierPipeline,maxpri=10]
java.lang.IllegalThreadStateException
    at java.lang.ThreadGroup.destroy (ThreadGroup.java:775)
    at org.codehaus.mojo.exec.ExecJavaMojo.execute (ExecJavaMojo.java:293)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:567)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  45.448 s
[INFO] Finished at: 2020-08-26T13:59:33+10:00
[INFO] ------------------------------------------------------------------------
```
