### ISSUE TITLE
Getting MySqlConnection error

### ISSUE THREAD

**Issue by prayag1m95** [GoogleCloudPlatform/DataflowTemplates#148]
When I try running the cdc-parent code in eclipse it gives me following error -

ERROR embedded.EmbeddedEngine: Unable to initialize and start connector's task class 'io.debezium.connector.mysql.MySqlConnectorTask' with config:

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at io.debezium.connector.mysql.MySqlJdbcContext.querySystemVariables(MySqlJdbcContext.java:299)
        at io.debezium.connector.mysql.MySqlJdbcContext.readMySqlSystemVariables(MySqlJdbcContext.java:280)
        at io.debezium.connector.mysql.MySqlTaskContext.<init>(MySqlTaskContext.java:81)
        at io.debezium.connector.mysql.MySqlTaskContext.<init>(MySqlTaskContext.java:53)
        at io.debezium.connector.mysql.MySqlConnectorTask.createAndStartTaskContext(MySqlConnectorTask.java:331)
        at io.debezium.connector.mysql.MySqlConnectorTask.start(MySqlConnectorTask.java:136)
        at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:49)
        at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:791)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

Also, google_application_credentials gives me null output.

**Comment by mariana-vc** [comment]
how did you solve this? I'm having the same error

**Comment by bvolpato** [comment]
I believe there are missing parts of the stack trace here, under `Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure`.

It would probably reveal the root cause of the connection (which is usually related to networking / firewall).

--

This issue has been stale for some time now. Please reopen it if there is a follow up or any related questions.
