### ISSUE TITLE
GCP Dataflow CDC Example Not Working

### ISSUE THREAD

**Issue by mayurmangire** [GoogleCloudPlatform/DataflowTemplates#184]
We are trying to set up Postgres to BIgquery replication using GCP Dataflow CDC: https://github.com/GoogleCloudPlatform/DataflowTemplates/tree/master/v2/cdc-parent

We have successfully installed debezium using docker. However, getting below exception while running the Docker container
 
org.apache.kafka.connect.errors.ConnectException: Cannot create replication connection
        at io.debezium.connector.postgresql.connection.PostgresReplicationConnection.<init>(PostgresReplicationConnection.java:101)
        at io.debezium.connector.postgresql.connection.PostgresReplicationConnection.<init>(PostgresReplicationConnection.java:47)
        at io.debezium.connector.postgresql.connection.PostgresReplicationConnection$ReplicationConnectionBuilder.build(PostgresReplicationConnection.java:478)
        at io.debezium.connector.postgresql.PostgresTaskContext.createReplicationConnection(PostgresTaskContext.java:111)
        at io.debezium.connector.postgresql.RecordsStreamProducer.<init>(RecordsStreamProducer.java:85)
        at io.debezium.connector.postgresql.RecordsSnapshotProducer.<init>(RecordsSnapshotProducer.java:76)
        at io.debezium.connector.postgresql.PostgresConnectorTask.createRecordProducer(PostgresConnectorTask.java:134)
        at io.debezium.connector.postgresql.PostgresConnectorTask.start(PostgresConnectorTask.java:113)
        at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:49)
        at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:791)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.debezium.jdbc.JdbcConnectionException: ERROR: could not access file "decoderbufs": No such file or directory
        at io.debezium.connector.postgresql.connection.PostgresReplicationConnection.initReplicationSlot(PostgresReplicationConnection.java:175)
        at io.debezium.connector.postgresql.connection.PostgresReplicationConnection.<init>(PostgresReplicationConnection.java:93)
        ... 14 more
Caused by: org.postgresql.util.PSQLException: ERROR: could not access file "decoderbufs": No such file or directory
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
        at org.postgresql.replication.fluent.logical.LogicalCreateSlotBuilder.make(LogicalCreateSlotBuilder.java:48)
        at io.debezium.connector.postgresql.connection.PostgresReplicationConnection.initReplicationSlot(PostgresReplicationConnection.java:136)

**Comment by saifabid** [comment]
I was able to overcome this with going here: `https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/master/v2/cdc-parent/cdc-embedded-connector/src/main/java/com/google/cloud/dataflow/cdc/connector/DebeziumToPubSubDataSender.java#L127` and adding in             `.with("plugin.name", "wal2json")`.
