### ISSUE TITLE
PERMISSION_DENIED: No permission to create Entry Group while running with GCP service account

### ISSUE THREAD

**Issue by kumararunpathak** [GoogleCloudPlatform/DataflowTemplates#198]
I was trying to run dabzeium connector locally through through docker using below command:

`docker run -v /Users/kumararun/workspace/oms/DataflowTemplates/v2/cdc-parent/application.properties:/etc/dataflow-cdc/dataflow_cdc.properties -v /Users/kumararun/workspace/oms/DataflowTemplates/v2/cdc-parent/dataflow_cdc_password.properties:/etc/dataflow-cdc/dataflow_cdc_password.properties -v /Users/kumararun/workspace/oms/DataflowTemplates/v2/cdc-parent/credential.json:/etc/gcp_credentials.json -e "GOOGLE_APPLICATION_CREDENTIALS=/etc/gcp_credentials.json" cdc-embedded-connector`

Service account credential contains below a list of permissions
Cloud SQL Client
Cloud Trace Agent
Kubernetes Engine Developer
Cloud Datastore User
Logs Writer
Monitoring Metric Writer
Monitoring Viewer
Pub/Sub Admin
Pub/Sub Publisher
Pub/Sub Subscriber
Pub/Sub Viewer
Cloud Memorystore Redis Viewer
Quota Viewer
Service Controller
Stackdriver Resource Metadata Writer
Storage Object Viewer

I am unable to know the exact missing permission. Below Exception, we are getting while running above docker command

`gcp_credentials.json" cdc-embedded-connector
Logger Binding: org.slf4j.impl.Log4jLoggerFactory@4501b7af
org.slf4j.impl.Log4jLoggerFactory
Exception in thread "main" com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: No permission to create Entry Group "cdc_debezium" or its parent resource does not exist.
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:55)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1349)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1024)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:866)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:711)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:520)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:495)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at com.google.cloud.datacatalog.v1beta1.DataCatalogClient.createEntryGroup(DataCatalogClient.java:739)
		at com.google.cloud.dataflow.cdc.common.DataCatalogSchemaUtils$SingleTopicSchemaManager.createEntryGroup(DataCatalogSchemaUtils.java:232)
		at com.google.cloud.dataflow.cdc.common.DataCatalogSchemaUtils$SingleTopicSchemaManager.<init>(DataCatalogSchemaUtils.java:205)
		at com.google.cloud.dataflow.cdc.common.DataCatalogSchemaUtils.getSchemaManager(DataCatalogSchemaUtils.java:75)
		at com.google.cloud.dataflow.cdc.common.DataCatalogSchemaUtils.getSchemaManager(DataCatalogSchemaUtils.java:68)
		at com.google.cloud.dataflow.cdc.connector.DebeziumToPubSubDataSender.run(DebeziumToPubSubDataSender.java:172)
		at com.google.cloud.dataflow.cdc.connector.App.startSender(App.java:228)
		at com.google.cloud.dataflow.cdc.connector.App.main(App.java:131)
Caused by: io.grpc.StatusRuntimeException: PERMISSION_DENIED: No permission to create Entry Group "cdc_debezium" or its parent resource does not exist.
	at io.grpc.Status.asRuntimeException(Status.java:533)
	... 24 more`

Below is our configurations:
databaseManagementSystem=mysql
databaseName=*******
databaseUsername=****
databaseAddress=34.**.112.**
databasePort=3306
gcpProject=********  
gcpPubsubTopicPrefix=debezium
whitelistedTables=********
singleTopicMode=true

Please suggest if we are missing any steps or any configurations value

**Comment by karunakarv** [comment]
I am also facing the same issue but i am deploying in GKE. @kumararunpathak  did you find any solution to this?

**Comment by gmaheshwari80** [comment]
I am also seeing the same error on GKE. any solution?  @kumararunpathak

**Comment by karunakarv** [comment]
@gmaheshwari please check whether service account has the proper permission to create Entry Group.

**Comment by gmaheshwari80** [comment]
@karunakarv permission is fine. it went fine at startup and entry group got created initially. It gave this error after a few days of connector running.

**Comment by karunakarv** [comment]
@gmaheshwari80 for me, entry group is getting created and a custom entry is created. After that getting an error now. 
Error is: "Error : common.DataCatalogSchemaUtils: Entry group name <my entry group name>". No other details about the error is available.

**Comment by gmaheshwari80** [comment]
Your error seems to be different than mine, but something related to permission. My service credential has data catalog admin permission.


Exception in thread "main" com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Request had insufficient authentication scopes. at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:55) at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72) at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60) at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97) at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68) at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1349) at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398) at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1024) at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:866) at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:711) at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:520) at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:495) at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700) at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399) at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510) at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66) at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630) at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518) at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692) at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681) at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57) at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112) at com.google.cloud.datacatalog.v1beta1.DataCatalogClient.createEntryGroup(DataCatalogClient.java:739) at com.google.cloud.dataflow.cdc.common.DataCatalogSchemaUtils$SingleTopicSchemaManager.createEntryGroup(DataCatalogSchemaUtils.java:232) at com.google.cloud.dataflow.cdc.common.DataCatalogSchemaUtils$SingleTopicSchemaManager.<init>(DataCatalogSchemaUtils.java:205) at com.google.cloud.dataflow.cdc.common.DataCatalogSchemaUtils.getSchemaManager(DataCatalogSchemaUtils.java:75) at com.google.cloud.dataflow.cdc.common.DataCatalogSchemaUtils.getSchemaManager(DataCatalogSchemaUtils.java:68) at com.google.cloud.dataflow.cdc.connector.DebeziumToPubSubDataSender.run(DebeziumToPubSubDataSender.java:184) at com.google.cloud.dataflow.cdc.connector.App.startSender(App.java:231) at com.google.cloud.dataflow.cdc.connector.App.main(App.java:131) Caused by: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Request had insufficient authentication scopes. at io.grpc.Status.asRuntimeException(Status.java:533) ... 24 more

**Comment by bvolpato** [comment]
Please enable Data Catalog APIs prior to running that template: https://console.cloud.google.com/marketplace/product/google/datacatalog.googleapis.com

--

This issue has been stale for some time now. Please reopen it if there is a follow up or any related questions.
