### ISSUE TITLE
PubSub to BQ deadletter table

### ISSUE THREAD

**Issue by pdeyhim** [GoogleCloudPlatform/DataflowTemplates#22]
Seeing the following error which seems to be an uncaught exception which I believe is skipping the deadletter table: 

java.lang.RuntimeException: java.io.IOException: Insert failed: [{"errors":[{"debugInfo":"","location":"location.latitude","message":"Cannot convert value to floating point (bad value):","reason":"invalid"}],"index":0}, {"errors":[{"debugInfo":"","location":"","message":"","reason":"stopped"}],"index":1}, {"errors":[{"debugInfo":"","location":"","message":"","reason":"stopped"}],"index":2}, {"errors":[{"debugInfo":"","location":"","message":"","reason":"stopped"}],"index":3}, {"errors":[{"debugInfo":"","location":"","message":"","reason":"stopped"}],"index":4}, {"errors":[{"debugInfo":"","location":"","message":"","reason":"stopped"}],"index":5}, {"errors":[{"debugInfo":"","location":"","message":"","reason":"stopped"}],"index":6}, {"errors":
...[{"debugInfo":"","location":"","message":"","reason":"stopped"}],"index":209}]
	at org.apache.beam.sdk.io.gcp.bigquery.StreamingWriteFn.flushRows(StreamingWriteFn.java:142)
	at org.apache.beam.sdk.io.gcp.bigquery.StreamingWriteFn.finishBundle(StreamingWriteFn.java:103)
Caused by: java.io.IOException: Insert failed: [{"errors":[{"debugInfo":"","location":"location.latitude","message":"Cannot convert value to floating point (bad value):","reason":"invalid"}],"index":0}, {"errors":[{"debugInfo":"","location":"","message":"","reason":"stopped"}],"index":1}, {"errors":[{"debugInfo":"","location":"","message":"","reason":"stopped"}],"index":2}, {"errors":[{"debugInfo":"","location":"","message":"","reason":"stopped"}],"index":3}, {"errors":[{"debugInfo":"","location":"","message":"","reason":"stopped"}],"index":4}, {"errors": ...

**Comment by JessieJingxuGao** [comment]
Got the same error... Is there any fix or hint on this now?
