### ISSUE TITLE
ERROR : Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project cdc-embedded-connector: An exception occured while executing the Java class. io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission denied on resource project ...

### ISSUE THREAD

**Issue by DavidTanjaya** [GoogleCloudPlatform/DataflowTemplates#240]
Anybody know why this happened ?? i've been figure it out about this and got nothing. Thanks for your answer

[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.google.cloud.dataflow.cdc:cdc-change-applier:jar:0.1
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:exec-maven-plugin is missing. @ line 30, column 15
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.google.cloud.dataflow.cdc:cdc-embedded-connector:jar:0.1
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:exec-maven-plugin is missing. @ line 37, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building cdc-embedded-connector 0.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:3.0.0:java (default-cli) @ cdc-embedded-connector ---
Logger Binding: org.slf4j.impl.Log4jLoggerFactory@2b2181aa
org.slf4j.impl.Log4jLoggerFactory
[WARNING] 
com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission denied on resource project DWH-Project.
        at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:55)
        at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
        at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
        at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
       at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
        at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1349)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1024)
        at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:866)
        at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:711)
        at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:520)
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:495)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
                at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
                at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
                at com.google.cloud.datacatalog.v1beta1.DataCatalogClient.createEntryGroup(DataCatalogClient.java:739)
                at com.google.cloud.dataflow.cdc.common.DataCatalogSchemaUtils$SingleTopicSchemaManager.createEntryGroup(DataCatalogSchemaUtils.java:232)
                at com.google.cloud.dataflow.cdc.common.DataCatalogSchemaUtils$SingleTopicSchemaManager.<init>(DataCatalogSchemaUtils.java:205)
                at com.google.cloud.dataflow.cdc.common.DataCatalogSchemaUtils.getSchemaManager(DataCatalogSchemaUtils.java:75)
                at com.google.cloud.dataflow.cdc.common.DataCatalogSchemaUtils.getSchemaManager(DataCatalogSchemaUtils.java:68)
                at com.google.cloud.dataflow.cdc.connector.DebeziumToPubSubDataSender.run(DebeziumToPubSubDataSender.java:172)
                at com.google.cloud.dataflow.cdc.connector.App.startSender(App.java:228)
                at com.google.cloud.dataflow.cdc.connector.App.main(App.java:131)
                at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
                ... 1 more
Caused by: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission denied on resource project DWH-Project.
        at io.grpc.Status.asRuntimeException(Status.java:533)
        ... 24 more
[WARNING] thread Thread[Gax-1,5,com.google.cloud.dataflow.cdc.connector.App] was interrupted but is still alive after waiting at least 15000msecs
[WARNING] thread Thread[Gax-1,5,com.google.cloud.dataflow.cdc.connector.App] will linger despite being asked to die via interruption
[WARNING] thread Thread[grpc-default-worker-ELG-1-1,5,com.google.cloud.dataflow.cdc.connector.App] will linger despite being asked to die via interruption
[WARNING] thread Thread[grpc-default-executor-0,5,com.google.cloud.dataflow.cdc.connector.App] will linger despite being asked to die via interruption
[WARNING] thread Thread[grpc-default-worker-ELG-1-2,5,com.google.cloud.dataflow.cdc.connector.App] will linger despite being asked to die via interruption
[WARNING] thread Thread[grpc-default-worker-ELG-1-3,5,com.google.cloud.dataflow.cdc.connector.App] will linger despite being asked to die via interruption
[WARNING] thread Thread[Gax-2,5,com.google.cloud.dataflow.cdc.connector.App] will linger despite being asked to die via interruption
[WARNING] thread Thread[Gax-3,5,com.google.cloud.dataflow.cdc.connector.App] will linger despite being asked to die via interruption
[WARNING] thread Thread[Gax-4,5,com.google.cloud.dataflow.cdc.connector.App] will linger despite being asked to die via interruption
[WARNING] NOTE: 8 thread(s) did not finish despite being asked to  via interruption. This is not a problem with exec:java, it is a problem with the running code. Although not serious, it should be remedied.
[WARNING] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=com.google.cloud.dataflow.cdc.connector.App,maxpri=10]
java.lang.IllegalThreadStateException
        at java.lang.ThreadGroup.destroy(ThreadGroup.java:778)
        at org.codehaus.mojo.exec.ExecJavaMojo.execute(ExecJavaMojo.java:293)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20.520s
[INFO] Finished at: Fri Apr 09 04:41:09 UTC 2021
[INFO] Final Memory: 26M/234M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project cdc-embedded-connector: An exception occured while executing the Java class. io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission denied on resource project DWH-Project. -> [Help 1]

**Comment by DavidTanjaya** [comment]
by the way, im using vm instance from gcp console

**Comment by pabloem** [comment]
I believe Data Catalog does not support using your default credentials. You
need to use a service account credential to use service catalog.

**Comment by DavidTanjaya** [comment]
ahh, i missed it. Thank you i fixed the problem, but i got another error like this 

ERROR common.BaseSourceTask: The 'database.dbname' value is invalid: A value is required
21/04/19 03:31:27 ERROR embedded.EmbeddedEngine: Unable to initialize and start connector's task class 'io.debezium.connector.postgresql.PostgresConnectorTask' with config: {table.whitelist=testdb.company, database.port=5431, java.runtime.name=OpenJDK Runtime Environment, java.vm.version=25.282-b08, sun.boot.library.path=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64/jre/lib/amd64, database.password=********, java.vm.vendor=Red Hat, Inc., java.vendor.url=https://www.redhat.com/, guice.disable.misplaced.annotation.check=true, path.separator=:, java.vm.name=OpenJDK 64-Bit Server VM, file.encoding.pkg=sun.io, sun.os.patch.level=unknown, database.history.file.filename=/opt/dataflow-cdc/offset/database-history.dat, user.country=US, sun.java.launcher=SUN_STANDARD, java.vm.specification.name=Java Virtual Machine Specification, user.dir=/root/DataflowTemplates/v2/cdc-parent, java.runtime.version=1.8.0_282-b08, java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment, os.arch=amd64, java.endorsed.dirs=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64/jre/lib/endorsed, java.io.tmpdir=/tmp, name=debezium-to-pubsub-connector, line.separator=
, offset.storage=org.apache.kafka.connect.storage.FileOffsetBackingStore, java.vm.specification.vendor=Oracle Corporation, os.name=Linux, classworlds.conf=/usr/share/maven/bin/m2.conf, sun.jnu.encoding=UTF-8, java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib, java.class.version=52.0, java.specification.name=Java Platform API Specification, sun.management.compiler=HotSpot 64-Bit Tiered Compilers, offset.flush.interval.ms=10000, os.version=3.10.0-1160.24.1.el7.x86_64, user.home=/root, user.timezone=UTC, java.awt.printerjob=sun.print.PSPrinterJob, file.encoding=UTF-8, java.specification.version=1.8, user.name=root, java.class.path=/usr/share/maven/boot/plexus-classworlds.jar, java.vm.specification.version=1.8, sun.arch.data.model=64, sun.java.command=org.codehaus.plexus.classworlds.launcher.Launcher -Ppostgres exec:java -pl cdc-embedded-connector -Dexec.args=cdc-embedded-connector/src/main/resources/dataflow_cdc.properties, java.home=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64/jre, user.language=en, java.specification.vendor=Oracle Corporation, awt.toolkit=sun.awt.X11.XToolkit, java.vm.info=mixed mode, database.hostname=localhost, java.version=1.8.0_282, java.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64/jre/lib/ext:/usr/java/packages/lib/ext, sun.boot.class.path=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64/jre/lib/resources.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64/jre/lib/rt.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64/jre/lib/jsse.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64/jre/lib/jce.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64/jre/lib/charsets.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64/jre/lib/jfr.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64/jre/classes, java.vendor=Red Hat, Inc., maven.home=/usr/share/maven, file.separator=/, database.server.name=testdb, java.vendor.url.bug=https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20Enterprise%20Linux%207&component=java-1.8.0-openjdk, offset.storage.file.filename=/opt/dataflow-cdc/offset/offset-tracker, database.user=tester, sun.io.unicode.encoding=UnicodeLittle, sun.cpu.endian=little, decimal.handling.mode=string, connector.class=io.debezium.connector.postgresql.PostgresConnector, database.history=io.debezium.relational.history.FileDatabaseHistory, exec.args=cdc-embedded-connector/src/main/resources/dataflow_cdc.properties, sun.cpu.isalist=}
org.apache.kafka.connect.errors.ConnectException: Error configuring an instance of PostgresConnectorTask; check the logs for details

it said database.dbname value invalid, but i think it's correct

the properties:
databaseName=testdb
databaseUsername=tester
databaseAddress=localhost
databasePort=5431
gcpProject=dwh-project-303207
gcpPubsubTopicPrefix=test_
whitelistedTables=testdb.testdb.company
databasePassword=password
singleTopicMode=true
databaseManagementSystem=postgres
