### ISSUE TITLE
cdc-embedded-connector does not work with current dependencies

### ISSUE THREAD

**Issue by seitau** [GoogleCloudPlatform/DataflowTemplates#266]
### Environment
```sh
$ uname -a
Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
```
```sh
$ mvn --version
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /usr/local/Cellar/maven/3.8.1/libexec
Java version: 16.0.1, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk/16.0.1/libexec/openjdk.jdk/Contents/Home
Default locale: ja_JP, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"
```

### Details
I was trying to set up cdc-embedded-connector with singleTopicMode=true following README but it didn't work with latest(e2ea097b9449e04c135ef15ebc2d4a17a307091c) version while it worked with previous(cd019691b78654ba70957f4f66b8ef5da85ba652) version.

Below is the full stack trace of the error:
<details>
<summary>stack trace</summary>
<p>

```sh
docker run --rm -v $(pwd)/config/dataflow_cdc.properties:/etc/dataflow-cdc/dataflow_cdc.properties -v $(pwd)/config/dataflow_cdc_password.properties:/etc/dataflow-cdc/dataflow_cdc_password.properties -v $HOME/.config/gcloud/application_default_credentials.json:/etc/gcp_credentials.json -e "GOOGLE_APPLICATION_CREDENTIALS=/etc/gcp_credentials.json" cdc-embedded-connector
Logger Binding: org.slf4j.impl.Log4jLoggerFactory@59fa1d9b
org.slf4j.impl.Log4jLoggerFactory
Exception in thread "main" java.lang.NoClassDefFoundError: io/grpc/internal/BaseDnsNameResolverProvider
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at io.grpc.ServiceProviders.loadAll(ServiceProviders.java:67)
        at io.grpc.NameResolverRegistry.getDefaultRegistry(NameResolverRegistry.java:101)
        at io.grpc.internal.ManagedChannelImplBuilder.<init>(ManagedChannelImplBuilder.java:107)
        at io.grpc.internal.ManagedChannelImplBuilder.<init>(ManagedChannelImplBuilder.java:228)
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<init>(NettyChannelBuilder.java:184)
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.forTarget(NettyChannelBuilder.java:151)
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.forAddress(NettyChannelBuilder.java:134)
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:38)
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:24)
        at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:270)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1500(InstantiatingGrpcChannelProvider.java:71)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:202)
        at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:209)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:192)
        at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:155)
        at com.google.cloud.datacatalog.v1beta1.stub.GrpcDataCatalogStub.create(GrpcDataCatalogStub.java:358)
        at com.google.cloud.datacatalog.v1beta1.stub.DataCatalogStubSettings.createStub(DataCatalogStubSettings.java:314)
        at com.google.cloud.datacatalog.v1beta1.DataCatalogClient.<init>(DataCatalogClient.java:472)
        at com.google.cloud.datacatalog.v1beta1.DataCatalogClient.create(DataCatalogClient.java:453)
        at com.google.cloud.datacatalog.v1beta1.DataCatalogClient.create(DataCatalogClient.java:445)
        at com.google.cloud.dataflow.cdc.common.DataCatalogSchemaUtils$DataCatalogSchemaManager.setupDataCatalogClient(DataCatalogSchemaUtils.java:191)
        at com.google.cloud.dataflow.cdc.common.DataCatalogSchemaUtils$SingleTopicSchemaManager.createEntryGroup(DataCatalogSchemaUtils.java:212)
        at com.google.cloud.dataflow.cdc.common.DataCatalogSchemaUtils$SingleTopicSchemaManager.<init>(DataCatalogSchemaUtils.java:205)
        at com.google.cloud.dataflow.cdc.common.DataCatalogSchemaUtils.getSchemaManager(DataCatalogSchemaUtils.java:75)
        at com.google.cloud.dataflow.cdc.common.DataCatalogSchemaUtils.getSchemaManager(DataCatalogSchemaUtils.java:68)
        at com.google.cloud.dataflow.cdc.connector.DebeziumToPubSubDataSender.run(DebeziumToPubSubDataSender.java:172)
        at com.google.cloud.dataflow.cdc.connector.App.startSender(App.java:228)
        at com.google.cloud.dataflow.cdc.connector.App.main(App.java:131)
Caused by: java.lang.ClassNotFoundException: io.grpc.internal.BaseDnsNameResolverProvider
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 47 more

```
</p>
</details> 

As in the error, it seems to be caused by dependencies around grpc introduced by commit(e2ea097b9449e04c135ef15ebc2d4a17a307091c).

**Comment by heromanba** [comment]
> ### Environment
> ```shell
> $ uname -a
> Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
> ```
> 
> ```shell
> $ mvn --version
> Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
> Maven home: /usr/local/Cellar/maven/3.8.1/libexec
> Java version: 16.0.1, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk/16.0.1/libexec/openjdk.jdk/Contents/Home
> Default locale: ja_JP, platform encoding: UTF-8
> OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"
> ```
> 
> ### Details
> I was trying to set up cdc-embedded-connector with singleTopicMode=true following README but it didn't work with latest([e2ea097](https://github.com/GoogleCloudPlatform/DataflowTemplates/commit/e2ea097b9449e04c135ef15ebc2d4a17a307091c)) version while it worked with previous([cd01969](https://github.com/GoogleCloudPlatform/DataflowTemplates/commit/cd019691b78654ba70957f4f66b8ef5da85ba652)) version.
> 
> Below is the full stack trace of the error:
> 
> stack trace
> As in the error, it seems to be caused by dependencies around grpc introduced by commit([e2ea097](https://github.com/GoogleCloudPlatform/DataflowTemplates/commit/e2ea097b9449e04c135ef15ebc2d4a17a307091c)).

Note that for Apple M1 chip, if we directly switch to [e2ea097](https://github.com/GoogleCloudPlatform/DataflowTemplates/commit/e2ea097b9449e04c135ef15ebc2d4a17a307091c), an error might happen when `mvn install`:
```
[ERROR] testSchemasEmittedOnlyOnChanges  Time elapsed: 0.618 s  <<< ERROR!
org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] no native library is found for os.name=Mac and os.arch=aarch64
        at com.google.cloud.dataflow.cdc.applier.BigQueryChangeApplierTest.testSchemasEmittedOnlyOnChanges(BigQueryChangeApplierTest.java:89)
```
To solve this, we can simply change `beam.version` to `2.29.0`.
