### ISSUE TITLE
BulkDecompressor -- Error writing failures CSV file

### ISSUE THREAD

**Issue by alec-ferguson-sunrun** [GoogleCloudPlatform/DataflowTemplates#33]
When BulkDecompressor tries to write an error CSV file, seeing this stack trace:
```
Caused by: java.lang.IllegalArgumentException: No quotes mode set but no escape character is set
	at org.apache.commons.csv.CSVFormat.validate(CSVFormat.java:1397)
	at org.apache.commons.csv.CSVFormat.<init>(CSVFormat.java:647)
	at org.apache.commons.csv.CSVFormat.withQuoteMode(CSVFormat.java:1832)
	at com.google.cloud.teleport.templates.BulkDecompressor.lambda$run$9962e4b6$1(BulkDecompressor.java:234)
	at org.apache.beam.sdk.transforms.Contextful.lambda$fn$36334a93$1(Contextful.java:112)
	at org.apache.beam.sdk.transforms.MapElements$1.processElement(MapElements.java:123)
```

From reading the CSVFormat code, it looks like you need to call `withEscape()` before you call `withQuoteMode()`. I will have a pull request to fix this shortly.

**Comment by azurezyq** [comment]
Thank you for reporting this. I read the codes and I think you are right. But the template is running fine in our integration testing environment. I'll try to figure out why it is the case.

looking forward to your PR.

**Comment by alec-ferguson-sunrun** [comment]
Thanks @azurezyq !

The template works fine if the files have valid extensions. Perhaps your tests only have valid extensions? Thus they don't try to write a CSV file, and don't hit this code? I discovered this because my files had extension `.gzip`, which is apparently not supported.

Arguably this is more of a bug in `CSVFormat`. The builder shouldn't care what order you specify properties in.
https://github.com/apache/commons-csv/blob/master/src/main/java/org/apache/commons/csv/CSVFormat.java#L1651
