### ISSUE TITLE
[Bug]: Unable to initialize and start debezium connector for Postgres

### ISSUE THREAD

**Issue by nidzo17** [GoogleCloudPlatform/DataflowTemplates#351]
### Related Template(s)

cdc

### What happened?

Unable to initialize and start connector error. I tried many different .properties and the same error occurs on both CloudSQL and local Postgres instances and on both Cloud Shell and local CLI.
psql or gcloud onnection to the postgres work.

.properties example:
databaseName=debezium-testing-db
databaseUsername=username
databaseAddress=ip_address
databasePort=5432
gcpProject=project_id
gcpPubsubTopicPrefix=stream_test_
whitelistedTables=debezium-testing-db.schema.table_name, debezium-testing-db.table_name
databasePassword=password
databaseManagementSystem=postgres
inMemoryOffsetStorage=true
debezium.database.dbname=debezium-testing-db

### Beam Version

2.35.0

### Relevant log output

```shell
mvn -Ppostgres -e -X exec:java -pl cdc-embedded-connector -Dexec.args="/cloudshell_open/DataflowTemplates/v2/cdc-parent/cdc-embedded-connector/src/main/resources/dataflow_cdc.properties

[com.google.cloud.dataflow.cdc.connector.App.main()] INFO com.google.cloud.dataflow.cdc.connector.DebeziumToPubSubDataSender - Initializing Debezium Embedded Engine
[pool-1-thread-1] ERROR io.debezium.embedded.EmbeddedEngine - Unable to initialize and start connector's task class 'io.debezium.connector.postgresql.PostgresConnectorTask' with config ...
org.apache.kafka.connect.errors.ConnectException: Could not initialize type registry
        at io.debezium.connector.postgresql.connection.PostgresConnection.<init>(PostgresConnection.java:89)
        at io.debezium.connector.postgresql.PostgresConnectorTask.start(PostgresConnectorTask.java:70)
        at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:49)
        at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:791)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:292)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
        at org.postgresql.Driver.makeConnection(Driver.java:454)
        at org.postgresql.Driver.connect(Driver.java:256)
        at io.debezium.jdbc.JdbcConnection.lambda$patternBasedFactory$1(JdbcConnection.java:179)
        at io.debezium.jdbc.JdbcConnection.connection(JdbcConnection.java:756)
        at io.debezium.jdbc.JdbcConnection.connection(JdbcConnection.java:751)
        at io.debezium.connector.postgresql.connection.PostgresConnection.<init>(PostgresConnection.java:86)
        ... 8 more
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at org.postgresql.core.PGStream.<init>(PGStream.java:70)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:91)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
        ... 16 more
[DEBUG] joining on thread Thread[pool-1-thread-1,5,com.google.cloud.dataflow.cdc.connector.App]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.248 s
[INFO] Finished at: 2022-02-09T14:02:54Z
[INFO] ------------------------------------------------------------------------
[Thread-1] INFO com.google.cloud.dataflow.cdc.connector.DebeziumToPubSubDataSender - Requesting embedded engine to shut down

but sometimes these errors:
org.apache.kafka.connect.errors.ConnectException: Cannot create replication connection
	at io.debezium.connector.postgresql.connection.PostgresReplicationConnection.<init>(PostgresReplicationConnection.java:101)
	at io.debezium.connector.postgresql.connection.PostgresReplicationConnection.<init>(PostgresReplicationConnection.java:47)
	at io.debezium.connector.postgresql.connection.PostgresReplicationConnection$ReplicationConnectionBuilder.build(PostgresReplicationConnection.java:478)
	at io.debezium.connector.postgresql.PostgresTaskContext.createReplicationConnection(PostgresTaskContext.java:111)
	at io.debezium.connector.postgresql.RecordsStreamProducer.<init>(RecordsStreamProducer.java:85)
	at io.debezium.connector.postgresql.RecordsSnapshotProducer.<init>(RecordsSnapshotProducer.java:76)
	at io.debezium.connector.postgresql.PostgresConnectorTask.createRecordProducer(PostgresConnectorTask.java:134)
	at io.debezium.connector.postgresql.PostgresConnectorTask.start(PostgresConnectorTask.java:113)
	at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:49)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:791)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.debezium.jdbc.JdbcConnectionException: ERROR: could not access file "decoderbufs": No such file or directory
	at io.debezium.connector.postgresql.connection.PostgresReplicationConnection.initReplicationSlot(PostgresReplicationConnection.java:175)
	at io.debezium.connector.postgresql.connection.PostgresReplicationConnection.<init>(PostgresReplicationConnection.java:93)
	... 14 more
Caused by: org.postgresql.util.PSQLException: ERROR: could not access file "decoderbufs": No such file or directory
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
	at org.postgresql.replication.fluent.logical.LogicalCreateSlotBuilder.make(LogicalCreateSlotBuilder.java:48)
	at io.debezium.connector.postgresql.connection.PostgresReplicationConnection.initReplicationSlot(PostgresReplicationConnection.java:136)
	... 15 more
[DEBUG] joining on thread Thread[pool-1-thread-1,5,com.google.cloud.dataflow.cdc.connector.App]

```

**Comment by bvolpato** [comment]
https://github.com/GoogleCloudPlatform/DataflowTemplates/issues/95 and https://github.com/GoogleCloudPlatform/DataflowTemplates/issues/184 mention the need of wal2json plugin.

Can you please verify if that's what you need, too?
