### ISSUE TITLE
GroupByKey Exception in common/DatastoreConverters.java

### ISSUE THREAD

**Issue by miguelars23** [GoogleCloudPlatform/DataflowTemplates#5]
Trying to use the Pub/Sub to Datastore template I ran into the error described in this [StackOverflow thread](https://stackoverflow.com/questions/51890285/how-to-use-google-provided-template-pubsub-to-datastore). I tried the recommendation posted there, but then got the following exception:

java.lang.IllegalStateException: GroupByKey cannot be applied to non-bounded PCollection in the GlobalWindow without a trigger. Use a Window.into or Window.triggering transform prior to GroupByKey.
        at org.apache.beam.sdk.transforms.GroupByKey.applicableTo(GroupByKey.java:173)
        at org.apache.beam.sdk.transforms.GroupByKey.expand(GroupByKey.java:204)
        at org.apache.beam.sdk.transforms.GroupByKey.expand(GroupByKey.java:120)
        at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:537)
        at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:472)
        at org.apache.beam.sdk.values.PCollection.apply(PCollection.java:286)
        at com.google.cloud.teleport.templates.common.DatastoreConverters$CheckSameKey.expand(DatastoreConverters.java:210)
        at com.google.cloud.teleport.templates.common.DatastoreConverters$CheckSameKey.expand(DatastoreConverters.java:172)
        at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:537)
        at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:491)
        at org.apache.beam.sdk.values.PCollection.apply(PCollection.java:299)
        at com.google.cloud.teleport.templates.common.DatastoreConverters$WriteJsonEntities.expand(DatastoreConverters.java:158)
        at com.google.cloud.teleport.templates.common.DatastoreConverters$WriteJsonEntities.expand(DatastoreConverters.java:134)
        at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:537)
        at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:472)
        at org.apache.beam.sdk.values.PCollection.apply(PCollection.java:286)
        at com.google.cloud.teleport.templates.PubsubToDatastore.main(PubsubToDatastore.java:69)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
        at java.lang.Thread.run(Thread.java:748)

There is a workaround for this in [another StackOverflow thread](https://stackoverflow.com/questions/51926337/is-it-able-to-stream-data-from-pubsub-to-datastore-using-dataflow), that bypasses this issue, but it wouldn't hurt if someone can take a look at it. Thanks.

**Comment by dasoto** [comment]
Same issue. Is there any way to make the template code work?
