### ISSUE TITLE
Cassandra to Bigtable template: use Cassandra Query

### ISSUE THREAD

**Issue by acscott** [GoogleCloudPlatform/DataflowTemplates#574]
### Related Template(s)

v1/Cassandra to Bigtable

### What feature(s) are you requesting?

Can we provide a query for the CassandraIO.Read instead of specifying the table? We need to split out static columns from the table since bigtable doesn't support those.

I tried modifying `v1/src/main/java/com/google/cloud/teleport/bigtable/CassandraToBigtable.java`
with
```
 CassandraIO.Read<Row> source =
        CassandraIO.<Row>read()
            .withHosts(hosts)
            .withPort(options.getCassandraPort())
            .withKeyspace(options.getCassandraKeyspace())
            .withTable(options.getCassandraTable())
            .withQuery("SELECT DISTINCT locus_id, catalogs as c, created_at as i, dec as d, lightcurve as l, props as p, tags as t, ra as r, updated_at as u FROM antares_alerts_staging.locus;")
            .withUsername("secret")
            .withPassword("secret")
            .withMapperFactoryFn(cassandraObjectMapperFactory)
            .withEntity(Row.class)
            .withCoder(SerializableCoder.of(Row.class));

```
It compiles and runs, but the job errors with 
```
com.datastax.driver.core.exceptions.SyntaxError: line 1:167 mismatched input 'AND' expecting EOF (...as u FROM antares_alerts_staging.locus [AND]...)
	at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:52)
	at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:22)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:35)
	at com.datastax.driver.core.AbstractSession.prepare(AbstractSession.java:86)
	at org.apache.beam.sdk.io.cassandra.ReadFn.processElement(ReadFn.java:56)
	at org.apache.beam.sdk.io.cassandra.ReadFn$DoFnInvoker.invokeProcessElement(Unknown Source)
	at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:211)
```

**Comment by bvolpato** [comment]
Closing this, please tag/reopen if anything related is needed.
