### ISSUE TITLE
[Bug]: GCSToElasticsearch java.lang.IllegalArgumentException: TupleTag

### ISSUE THREAD

**Issue by xaleza** [GoogleCloudPlatform/DataflowTemplates#587]
### Related Template(s)

GCSToElasticsearch

### What happened?

Every time that I try to run this template, I get this error:
`java.lang.IllegalArgumentException: TupleTag Tag<com.google.cloud.teleport.v2.elasticsearch.templates.GCSToElasticsearch#0> not found in this PCollectionTuple tuple`

I also found another person with this error on [elastic forum](https://discuss.elastic.co/t/gcstoelasticsearch-template/323834).
Is it something that I am doing wrong? I've already tried with multiple data files on the bucket and none of them work.

### Beam Version

Newer than 2.43.0

### Relevant log output

```shell
{"severity":"INFO","time":"2023/02/10 11:45:23.626126","line":"java_template_launcher.go:40","message":"Started template launcher."}
{"severity":"INFO","time":"2023/02/10 11:45:23.626345","line":"java_template_launcher.go:44","message":"Initialize Java template."}
{"severity":"INFO","time":"2023/02/10 11:45:23.629093","line":"java_template.go:100","message":"Validating metadata template-container-args: {\"consoleLogsLocation\":\"gs://dataflow-staging-europe-west1-480258223563/staging/template_launches/2023-02-10_03_44_15-16589978667579574937/console_logs\",\"environment\":{\"additionalUserLabels\":{\"goog-dataflow-provided-template-name\":\"gcs_to_elasticsearch\",\"goog-dataflow-provided-template-type\":\"flex\"},\"region\":\"europe-west1\",\"serviceAccountEmail\":\"480258223563-compute@developer.gserviceaccount.com\",\"stagingLocation\":\"gs://dataflow-staging-europe-west1-480258223563/staging\",\"tempLocation\":\"gs://dataflow-staging-europe-west1-480258223563/tmp\"},\"jobId\":\"2023-02-10_03_44_15-16589978667579574937\",\"jobName\":\"gcs-to-elastic\",\"jobObjectLocation\":\"gs://dataflow-staging-europe-west1-480258223563/staging/template_launches/2023-02-10_03_44_15-16589978667579574937/job_object\",\"operationResultLocation\":\"gs://dataflow-staging-europe-west1-480258223563/staging/template_launches/2023-02-10_03_44_15-16589978667579574937/operation_result\",\"parameters\":{\"apiKey\":\"bGJNak80WUJSU2trZXhOMmVLbVI6VzJfSnFNU2hRLWk5MFB2LVdBblRMUQ==\",\"connectionUrl\":\"http://10.10.0.17:9200\",\"deadletterTable\":\"osgoqanalyticslab-536904:dataflow_test.error_queue\",\"index\":\"test\",\"inputFileSpec\":\"gs://wacs-to-elastic/topics/in_wacs_k8s_norm_events/partition=4/*.csv\",\"labels\":\"{\\n   \\\"goog-dataflow-provided-template-name\\\" : \\\"gcs_to_elasticsearch\\\",\\n   \\\"goog-dataflow-provided-template-type\\\" : \\\"flex\\\"\\n}\\n\",\"stagingLocation\":\"gs://dataflow-staging-europe-west1-480258223563/staging\",\"tempLocation\":\"gs://dataflow-staging-europe-west1-480258223563/tmp\",\"usePublicIps\":\"false\"},\"projectId\":\"osgoqanalyticslab-536904\"}"}
{"severity":"INFO","time":"2023/02/10 11:45:23.629588","line":"java_template.go:109","message":"Extracting operation result location."}
{"severity":"INFO","time":"2023/02/10 11:45:23.629619","line":"java_template.go:117","message":"Operation result location: gs://dataflow-staging-europe-west1-480258223563/staging/template_launches/2023-02-10_03_44_15-16589978667579574937/operation_result"}
{"severity":"INFO","time":"2023/02/10 11:45:23.629637","line":"java_template.go:120","message":"Extracting console log location."}
{"severity":"INFO","time":"2023/02/10 11:45:23.629654","line":"java_template.go:128","message":"Console logs location: gs://dataflow-staging-europe-west1-480258223563/staging/template_launches/2023-02-10_03_44_15-16589978667579574937/console_logs"}
{"severity":"INFO","time":"2023/02/10 11:45:23.629683","line":"java_template.go:131","message":"Extracting and validating Java command specs."}
{"severity":"INFO","time":"2023/02/10 11:45:23.629929","line":"java_template.go:139","message":"Generating launch args."}
{"severity":"INFO","time":"2023/02/10 11:45:23.629972","line":"java_args.go:136","message":"Overriding labels with value: {\"goog-dataflow-provided-template-type\":\"flex\", \"goog-dataflow-provided-template-name\":\"gcs_to_elasticsearch\"} (previous value: {\"goog-dataflow-provided-template-name\":\"gcs_to_elasticsearch\",\"goog-dataflow-provided-template-type\":\"flex\"})"}
{"severity":"INFO","time":"2023/02/10 11:45:23.629998","line":"java_args.go:136","message":"Overriding stagingLocation with value: gs://dataflow-staging-europe-west1-480258223563/staging (previous value: gs://dataflow-staging-europe-west1-480258223563/staging)"}
{"severity":"INFO","time":"2023/02/10 11:45:23.630017","line":"java_args.go:136","message":"Overriding tempLocation with value: gs://dataflow-staging-europe-west1-480258223563/tmp (previous value: gs://dataflow-staging-europe-west1-480258223563/tmp)"}
{"severity":"INFO","time":"2023/02/10 11:45:23.630039","line":"java_args.go:136","message":"Overriding labels with value: {\n   \"goog-dataflow-provided-template-name\" : \"gcs_to_elasticsearch\",\n   \"goog-dataflow-provided-template-type\" : \"flex\"\n}\n (previous value: {\"goog-dataflow-provided-template-type\":\"flex\", \"goog-dataflow-provided-template-name\":\"gcs_to_elasticsearch\"})"}
{"severity":"INFO","time":"2023/02/10 11:45:23.630083","line":"launch.go:50","message":"Validating ExpectedFeatures."}
{"severity":"INFO","time":"2023/02/10 11:45:23.630107","line":"launch.go:75","message":"Launching Java template."}
{"severity":"INFO","time":"2023/02/10 11:45:23.630132","line":"java_template.go:63","message":"Using launch args: [-cp /template/gcs-to-elasticsearch/gcs-to-elasticsearch-conscrypt.jar:/template/gcs-to-elasticsearch/*:/template/gcs-to-elasticsearch/libs/*:/template/gcs-to-elasticsearch/classes com.google.cloud.teleport.v2.elasticsearch.templates.GCSToElasticsearch --runner=DataflowRunner --templateLocation=gs://dataflow-staging-europe-west1-480258223563/staging/template_launches/2023-02-10_03_44_15-16589978667579574937/job_object --stagingLocation=gs://dataflow-staging-europe-west1-480258223563/staging --index=test --connectionUrl=http://10.10.0.17:9200 --jobName=gcs-to-elastic --labels={\n   \"goog-dataflow-provided-template-name\" : \"gcs_to_elasticsearch\",\n   \"goog-dataflow-provided-template-type\" : \"flex\"\n}\n --usePublicIps=false --deadletterTable=osgoqanalyticslab-536904:dataflow_test.error_queue --apiKey={{redacted}} --inputFileSpec=gs://wacs-to-elastic/topics/in_wacs_k8s_norm_events/partition=4/*.csv --project=osgoqanalyticslab-536904 --tempLocation=gs://dataflow-staging-europe-west1-480258223563/tmp --region=europe-west1 --serviceAccount=480258223563-compute@developer.gserviceaccount.com]"}
{"severity":"INFO","time":"2023/02/10 11:45:23.630173","line":"exec.go:38","message":"Executing: java -cp /template/gcs-to-elasticsearch/gcs-to-elasticsearch-conscrypt.jar:/template/gcs-to-elasticsearch/*:/template/gcs-to-elasticsearch/libs/*:/template/gcs-to-elasticsearch/classes com.google.cloud.teleport.v2.elasticsearch.templates.GCSToElasticsearch --runner=DataflowRunner --templateLocation=gs://dataflow-staging-europe-west1-480258223563/staging/template_launches/2023-02-10_03_44_15-16589978667579574937/job_object --stagingLocation=gs://dataflow-staging-europe-west1-480258223563/staging --index=test --connectionUrl=http://10.10.0.17:9200 --jobName=gcs-to-elastic --labels={\n   \"goog-dataflow-provided-template-name\" : \"gcs_to_elasticsearch\",\n   \"goog-dataflow-provided-template-type\" : \"flex\"\n}\n --usePublicIps=false --deadletterTable=osgoqanalyticslab-536904:dataflow_test.error_queue --apiKey=bGJNak80WUJSU2trZXhOMmVLbVI6VzJfSnFNU2hRLWk5MFB2LVdBblRMUQ== --inputFileSpec=gs://wacs-to-elastic/topics/in_wacs_k8s_norm_events/partition=4/*.csv --project=osgoqanalyticslab-536904 --tempLocation=gs://dataflow-staging-europe-west1-480258223563/tmp --region=europe-west1 --serviceAccount=480258223563-compute@developer.gserviceaccount.com"}
{"severity":"INFO","time":"2023/02/10 11:45:32.872859","line":"exec.go:66","message":"org.apache.beam.runners.dataflow.DataflowRunner - PipelineOptions.filesToStage was not specified. Defaulting to files from the classpath: will stage 2 files. Enable logging at DEBUG level to see which files will be staged."}
{"severity":"ERROR","time":"2023/02/10 11:45:34.122159","line":"exec.go:66","message":"com.google.cloud.teleport.v2.common.UncaughtExceptionLogger - The template launch failed.\njava.lang.IllegalArgumentException: TupleTag Tag\u003ccom.google.cloud.teleport.v2.elasticsearch.templates.GCSToElasticsearch#0\u003e not found in this PCollectionTuple tuple\n\tat org.apache.beam.sdk.values.PCollectionTuple.get(PCollectionTuple.java:222)\n\tat com.google.cloud.teleport.v2.transforms.CsvConverters$LineToFailsafeJson.expand(CsvConverters.java:368)\n\tat com.google.cloud.teleport.v2.transforms.CsvConverters$LineToFailsafeJson.expand(CsvConverters.java:300)\n\tat org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:548)\n\tat org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:499)\n\tat org.apache.beam.sdk.values.PCollectionTuple.apply(PCollectionTuple.java:263)\n\tat com.google.cloud.teleport.v2.elasticsearch.templates.GCSToElasticsearch.run(GCSToElasticsearch.java:155)\n\tat com.google.cloud.teleport.v2.elasticsearch.templates.GCSToElasticsearch.main(GCSToElasticsearch.java:98)\n"}
{"severity":"INFO","time":"2023/02/10 11:45:34.143231","line":"exec.go:52","message":"java failed with exit status 1"}
{"severity":"ERROR","time":"2023/02/10 11:45:34.143324","line":"launch.go:80","message":"Error: Template launch failed: exit status 1"}
{"severity":"INFO","time":"2023/02/10 11:45:34.143357","line":"launch.go:102","message":"Uploading console logs to GCS location: gs://dataflow-staging-europe-west1-480258223563/staging/template_launches/2023-02-10_03_44_15-16589978667579574937/console_logs"}
```

**Comment by bvolpato** [comment]
Is it a regression or first time using the template?

We have some automated tests and they are all passing, so I am assuming it's something more specific rather than generalized.

Stack trace leads me to something related to CSV headers. I assume your CSV has no headers? Can you share more details on how the input looks like?

**Comment by bvolpato** [comment]
No UDFs?

**Comment by st4r-fish** [comment]
I have the same issue.

Created a GCS bucket ("kas-cf-test"), uploaded the CSV file mentioned in the [blog post](https://www.elastic.co/blog/ingest-data-directly-from-google-cloud-storage-into-elastic-using-google-dataflow), created a dataset ("deadletter_dataflow") and an empty table ("errrors"), and created an API key in my self-managed ES cluster:
```
POST /_security/api_key
{
  "name": "dataflow-cf", 
  "role_descriptors": {
    "dataflow_writer": { 
      "index": [
        {
          "names": ["cftesting-*"],
          "privileges": ["all"]
        }
      ]
    }
  }
}
```

Filled out the form:
![image](https://user-images.githubusercontent.com/66311729/222422727-72377ddc-7d9e-4233-bcc1-f195f33c288b.png)
Then got the same error:
>com.google.cloud.teleport.v2.common.UncaughtExceptionLogger - The template launch failed.
java.lang.IllegalArgumentException: TupleTag Tag<com.google.cloud.teleport.v2.elasticsearch.templates.GCSToElasticsearch#0> not found in this PCollectionTuple tuple
	at org.apache.beam.sdk.values.PCollectionTuple.get(PCollectionTuple.java:222)
	at com.google.cloud.teleport.v2.transforms.CsvConverters$LineToFailsafeJson.expand(CsvConverters.java:368)
	at com.google.cloud.teleport.v2.transforms.CsvConverters$LineToFailsafeJson.expand(CsvConverters.java:300)
	at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:548)
	at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:499)
	at org.apache.beam.sdk.values.PCollectionTuple.apply(PCollectionTuple.java:263)
	at com.google.cloud.teleport.v2.elasticsearch.templates.GCSToElasticsearch.run(GCSToElasticsearch.java:155)
	at com.google.cloud.teleport.v2.elasticsearch.templates.GCSToElasticsearch.main(GCSToElasticsearch.java:98)

**Comment by bvolpato** [comment]
Are you setting true for the parameter `containsHeaders`?

```
    @TemplateParameter.Boolean(
        order = 2,
        optional = true,
        description = "Input CSV files contain a header record.",
        helpText =
            "Input CSV files contain a header record (true/false). Only required if reading CSV files.")
    @Default.Boolean(false)
    Boolean getContainsHeaders();
```

(It would be listed as optional in the UI.)

**Comment by st4r-fish** [comment]
No, I didn't touch the optional parameters at all. As I said, I followed the instructions in the blog post and used the earthquake CSV (which has headers).
