### ISSUE TITLE
[Bug]: <SSL certificate issue connecting from RDi to GitHub Enterprise Server> 

### ISSUE THREAD

**Issue by dwhitneyhlc** [GoogleCloudPlatform/DataflowTemplates#634]
### Related Template(s)

https://github.heartlandcoop.com/Heartland-Coop/HCOOP.git: cannot open git-upload-pack 

### What happened?

https://github.heartlandcoop.com/Heartland-Coop/HCOOP.git: cannot open git-upload-pack 
Caused by: javax.net.ssl.SSLHandshakeException: com.ibm.jsse2.util.h: PKIX path building failed: com.ibm.security.cert.IBMCertPathBuilderException: unable to find valid certification path to requested target 

 <SSL certificate issue connecting from RDi to GitHub Enterprise Server> 

### Beam Version

Newer than 2.43.0

### Relevant log output

```shell
!ENTRY org.eclipse.egit.ui 4 0 2023-03-20 14:37:42.029 

!MESSAGE https://github.heartlandcoop.com/Heartland-Coop/HCOOP.git: cannot open git-upload-pack 

!STACK 0 

org.eclipse.jgit.api.errors.TransportException: https://github.heartlandcoop.com/Heartland-Coop/HCOOP.git: cannot open git-upload-pack 

at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:221) 

at org.eclipse.jgit.api.LsRemoteCommand.call(LsRemoteCommand.java:159) 

at org.eclipse.egit.core.op.ListRemoteOperation.run(ListRemoteOperation.java:100) 

at org.eclipse.egit.ui.internal.clone.SourceBranchPage$8.run(SourceBranchPage.java:341) 

at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119) 

Caused by: org.eclipse.jgit.errors.TransportException: https://github.heartlandcoop.com/Heartland-Coop/HCOOP.git: cannot open git-upload-pack 

at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:551) 

at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:311) 

at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:198) 

... 4 more 

Caused by: javax.net.ssl.SSLHandshakeException: com.ibm.jsse2.util.h: PKIX path building failed: com.ibm.security.cert.IBMCertPathBuilderException: unable to find valid certification path to requested target 

at com.ibm.jsse2.k.a(k.java:43) 

at com.ibm.jsse2.av.a(av.java:722) 

at com.ibm.jsse2.D.a(D.java:121) 

at com.ibm.jsse2.D.a(D.java:572) 

at com.ibm.jsse2.E.a(E.java:585) 

at com.ibm.jsse2.E.a(E.java:479) 

at com.ibm.jsse2.D.s(D.java:286) 

at com.ibm.jsse2.D.a(D.java:251) 

at com.ibm.jsse2.av.a(av.java:788) 

at com.ibm.jsse2.av.i(av.java:45) 

at com.ibm.jsse2.av.a(av.java:637) 

at com.ibm.jsse2.av.startHandshake(av.java:1020) 

at com.ibm.net.ssl.www2.protocol.https.c.afterConnect(c.java:1) 

at com.ibm.net.ssl.www2.protocol.https.d.connect(d.java:72) 

at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1582) 

at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1510) 

at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:491) 

at com.ibm.net.ssl.www2.protocol.https.b.getResponseCode(b.java:81) 

at org.eclipse.jgit.transport.http.JDKHttpConnection.getResponseCode(JDKHttpConnection.java:98) 

at org.eclipse.jgit.util.HttpSupport.response(HttpSupport.java:196) 

at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:489) 

... 6 more 

Caused by: com.ibm.jsse2.util.h: PKIX path building failed: com.ibm.security.cert.IBMCertPathBuilderException: unable to find valid certification path to requested target 

at com.ibm.jsse2.util.f.a(f.java:85) 

at com.ibm.jsse2.util.f.b(f.java:8) 

at com.ibm.jsse2.util.e.a(e.java:6) 

at com.ibm.jsse2.aD.a(aD.java:75) 

at com.ibm.jsse2.aD.a(aD.java:181) 

at com.ibm.jsse2.aD.checkServerTrusted(aD.java:144) 

at com.ibm.jsse2.E.a(E.java:145) 

... 22 more 

Caused by: com.ibm.security.cert.IBMCertPathBuilderException: unable to find valid certification path to requested target 

at com.ibm.security.cert.SunCertPathBuilder.build(SunCertPathBuilder.java:139) 

at com.ibm.security.cert.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:124) 

at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:292) 

at com.ibm.jsse2.util.f.a(f.java:129) 

... 28 more
```

**Comment by bvolpato** [comment]
Hi @dwhitneyhlc -- sorry, I don't see how this is related to the repository.

Can you elaborate?
